apiVersion: apps/v1
kind: Deployment
metadata:
  name: pservice-client-deployment
  labels:
    app: service-client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-client
  template:
    metadata:
      labels:
        app: service-client-deployment
    spec:
      containers:
        - name: service-client
          image: tallahmad/nguith2022:groupe3
          ports:
            - containerPort: 8081








---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    name: service-client-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort