version: '3.1'
services:
  app:
    container_name: groupE3up
    image: groupe3:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - db
  db:
    container_name: docker-db1
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: docker-db1
      MYSQL_ROOT_PASSWORD: tqll

    volumes:
      - ./db:/var/lib/mysql